name: Cypress Test

on:
  push:
    branches:
      - cypress

jobs:
  cypress-run:
    name: Cypress Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cypress Run
        uses: cypress-io/github-action@v2
        with:
          build: pnpm build
          start: pnpm start
